#!/usr/bin/env python3
"""
IRIB Live Channels Extractor
পার্সেস telewebion.ir থেকে লাইভ চ্যানেল তথ্য এবং m3u প্লেলিস্ট তৈরি করে
GitHub Actions এ প্রতি ঘণ্টায় চালানোর জন্য ডিজাইন করা হয়েছে

by @kgkaku
"""

import json
import requests
import time
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor, as_completed

# ==================== কনফিগারেশন ====================
CHANNEL_LIST_URL = "https://gateway.telewebion.ir/kandoo/channel/getChannelsList/?NumOfItems=300&v=4.4.1"
CHANNEL_DETAILS_URL = "https://gateway.telewebion.ir/kandoo/v3/channel/getChannelDetails/?Descriptor={}"
EPG_URL = "https://gateway.telewebion.ir/kandoo/channel/getChannelEPGbyDescriptor/?Descriptor={}"
STREAM_BASE_URL = "https://ncdn.telewebion.ir/{}/live/playlist.m3u8"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Mobile Safari/537.36",
    "Accept": "application/json, text/plain, */*",
    "Origin": "https://telewebion.ir",
    "Referer": "https://telewebion.ir/"
}

# গ্রুপ টাইপ ম্যাপিং (শুধু ইংরেজি নামের জন্য, API থেকে descriptor আসে)
GROUP_MAP = {
    "national": "National",
    "provincial": "Provincial",
    "exclusive": "Exclusive", 
    "international": "International",
    "radio": "Radio"
}

# ==================== ফাংশন ====================

def fetch_channels():
    """সব চ্যানেলের লিস্ট API থেকে নিয়ে আসে"""
    try:
        response = requests.get(CHANNEL_LIST_URL, headers=HEADERS, timeout=30)
        response.raise_for_status()
        data = response.json()
        return data.get("body", {}).get("queryChannel", [])
    except Exception as e:
        print(f"❌ চ্যানেল লিস্ট পেতে ব্যর্থ: {e}")
        return []

def fetch_channel_details(descriptor):
    """একটি চ্যানেলের ডিটেইলস (টোকেন সহ) API থেকে নিয়ে আসে"""
    try:
        url = CHANNEL_DETAILS_URL.format(descriptor)
        response = requests.get(url, headers=HEADERS, timeout=30)
        response.raise_for_status()
        data = response.json()
        channels = data.get("body", {}).get("queryChannel", [])
        return channels[0] if channels else None
    except Exception as e:
        return None

def fetch_epg(descriptor):
    """একটি চ্যানেলের EPG তথ্য API থেকে নিয়ে আসে"""
    try:
        url = EPG_URL.format(descriptor)
        response = requests.get(url, headers=HEADERS, timeout=30)
        response.raise_for_status()
        data = response.json()
        return data.get("body", {})
    except Exception as e:
        return None

def get_logo_url(image_name):
    """লোগো URL তৈরি করে"""
    if not image_name:
        return ""
    return f"https://gateway.telewebion.ir/kandoo/image/{image_name}"

def get_group_name(channel_type):
    """API থেকে প্রাপ্ত টাইপ ডিস্ক্রিপ্টর থেকে ইংরেজি গ্রুপ নাম"""
    if isinstance(channel_type, dict):
        descriptor = channel_type.get("descriptor", "national")
    else:
        descriptor = "national"
    return GROUP_MAP.get(descriptor, "General")

def get_epg_source(epg_data):
    """EPG ডাটা থেকে সোর্স URL বের করে"""
    if not epg_data:
        return ""
    # API রেসপন্স থেকে EPG URL বের করার চেষ্টা
    if isinstance(epg_data, dict):
        # বিভিন্ন সম্ভাব্য ফিল্ড চেক
        for field in ["epg_url", "source", "url", "link"]:
            if field in epg_data and epg_data[field]:
                return epg_data[field]
    return ""

def generate_m3u_content(channels, include_token=False):
    """Extvlcopt ফরম্যাটে m3u কন্টেন্ট জেনারেট করে"""
    m3u_lines = ['#EXTM3U', f'# Generated by @kgkaku - {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', '']
    
    for ch in channels:
        descriptor = ch.get("descriptor")
        name_en = ch.get("name_english", descriptor)
        name_fa = ch.get("name", descriptor)
        image_name = ch.get("image_name", "")
        channel_type = ch.get("type", {})
        
        # স্ট্রিম URL
        stream_url = STREAM_BASE_URL.format(descriptor)
        
        # লোগো URL
        logo_url = get_logo_url(image_name)
        
        # গ্রুপ নাম (API থেকে)
        group = get_group_name(channel_type)
        
        # EPG তথ্য (আলাদা API কল - একটু সময় নেবে)
        epg_data = fetch_epg(descriptor)
        epg_source = get_epg_source(epg_data)
        
        # tvg-id, tvg-name, tvg-logo সব ইংরেজিতে
        extinf = f'#EXTINF:-1 tvg-id="{descriptor}" tvg-name="{name_en}" tvg-logo="{logo_url}" group-title="{group}",{name_en}'
        
        # EPG থাকলে যোগ করব
        if epg_source:
            extinf += f' tvg-epg="{epg_source}"'
        
        m3u_lines.append(extinf)
        
        # Extvlcopt লাইন
        m3u_lines.append('#EXTVLCOPT:http-referrer=https://telewebion.ir/')
        m3u_lines.append('#EXTVLCOPT:http-user-agent=Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Mobile Safari/537.36')
        
        # টোকেন সহ সংস্করণ
        if include_token:
            details = fetch_channel_details(descriptor)
            if details and details.get("channel_token"):
                m3u_lines.append(f'#EXTVLCOPT:http-header=Authorization: Bearer {details["channel_token"]}')
        
        m3u_lines.append(stream_url)
        m3u_lines.append('')
    
    return '\n'.join(m3u_lines)

def generate_json_output(channels):
    """JSON আউটপুট জেনারেট করে (সব মেটাডাটা সহ, ডাইনামিক)"""
    output = {
        "generated": datetime.now().isoformat(),
        "credit": "@kgkaku",
        "total_channels": len(channels),
        "channels": []
    }
    
    for ch in channels:
        ch_info = {
            "descriptor": ch.get("descriptor"),
            "name_fa": ch.get("name"),
            "name_en": ch.get("name_english"),
            "type": ch.get("type", {}).get("name"),  # ফার্সি নাম
            "type_descriptor": ch.get("type", {}).get("descriptor"),  # ইংরেজি আইডি
            "group_name_en": get_group_name(ch.get("type")),  # ইংরেজি গ্রুপ নাম
            "has_archive": ch.get("has_archive", False),
            "priority": ch.get("priority"),
            "logo_url": get_logo_url(ch.get("image_name")),
            "stream_url": STREAM_BASE_URL.format(ch.get("descriptor")),
            "channel_id": ch.get("ChannelID")
        }
        
        # টোকেন তথ্য যোগ করা
        details = fetch_channel_details(ch.get("descriptor"))
        if details:
            ch_info["channel_token"] = details.get("channel_token")
            ch_info["epg_code"] = details.get("epg_code")
            ch_info["featured_image"] = details.get("featured_image")
        
        # EPG তথ্য যোগ করা
        epg_data = fetch_epg(ch.get("descriptor"))
        if epg_data:
            ch_info["epg"] = epg_data
        
        output["channels"].append(ch_info)
    
    return output

def save_outputs(channels):
    """সব আউটপুট ফাইল সেভ করে"""
    print(f"\n📺 মোট চ্যানেল: {len(channels)}")
    
    # টোকেন ছাড়া m3u (ইংরেজি নাম সহ)
    m3u_without_token = generate_m3u_content(channels, include_token=False)
    with open("irib_without_token.m3u", "w", encoding="utf-8") as f:
        f.write(m3u_without_token)
    print(f"✅ irib_without_token.m3u তৈরি হয়েছে")
    
    # টোকেন সহ m3u
    print("⏳ টোকেন সহ m3u তৈরি হচ্ছে...")
    m3u_with_token = generate_m3u_content(channels, include_token=True)
    with open("irib_with_token.m3u", "w", encoding="utf-8") as f:
        f.write(m3u_with_token)
    print(f"✅ irib_with_token.m3u তৈরি হয়েছে")
    
    # JSON আউটপুট
    json_output = generate_json_output(channels)
    with open("irib.json", "w", encoding="utf-8") as f:
        json.dump(json_output, f, ensure_ascii=False, indent=2)
    print(f"✅ irib.json তৈরি হয়েছে")
    
    # CREDITS ফাইল
    type_stats = {}
    for ch in channels:
        t = ch.get("type", {}).get("descriptor", "unknown")
        type_stats[t] = type_stats.get(t, 0) + 1
    
    with open("CREDITS.txt", "w", encoding="utf-8") as f:
        f.write(f"""
╔══════════════════════════════════════════════════════════════════════════════╗
║                         IRIB Live Channels Extractor                         ║
╠══════════════════════════════════════════════════════════════════════════════╣
║  Credit      : @kgkaku                                                       ║
║  Generated   : {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
║  Total       : {len(channels)} channels
╠══════════════════════════════════════════════════════════════════════════════╣
║  Channel Type Distribution:                                                  ║
""")
        for t, count in sorted(type_stats.items()):
            f.write(f"║    • {t.capitalize()}: {count} channels\n")
        f.write("""╚══════════════════════════════════════════════════════════════════════════════╝
""")
    print(f"✅ CREDITS.txt তৈরি হয়েছে")

# ==================== মেইন ফাংশন ====================

def main():
    print("=" * 60)
    print("IRIB Live Channels Extractor")
    print(f"by @kgkaku")
    print(f"Started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)
    
    # চ্যানেল লিস্ট ফেচ
    print("\n📡 ফেচ করা হচ্ছে চ্যানেল লিস্ট...")
    channels = fetch_channels()
    
    if not channels:
        print("❌ কোনো চ্যানেল পাওয়া যায়নি!")
        return
    
    print(f"✅ {len(channels)} টি চ্যানেল পাওয়া গেছে")
    
    # টাইপ অনুযায়ী কাউন্ট
    type_count = {}
    for ch in channels:
        t = ch.get("type", {}).get("descriptor", "unknown")
        type_count[t] = type_count.get(t, 0) + 1
    
    print("\n📊 চ্যানেল টাইপ ডিস্ট্রিবিউশন:")
    for t, count in type_count.items():
        print(f"   • {t}: {count}")
    
    # আউটপুট সেভ
    print("\n💾 আউটপুট ফাইল তৈরি করা হচ্ছে...")
    save_outputs(channels)
    
    print("\n" + "=" * 60)
    print("✅ সম্পন্ন!")
    print(f"📁 আউটপুট: irib_without_token.m3u, irib_with_token.m3u, irib.json, CREDITS.txt")
    print("=" * 60)

if __name__ == "__main__":
    main()
