name: Refresh Tamasha Playlist

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Cloudscraper
        # এখানে আমরা cloudscraper ইন্সটল করছি যা বট ডিটেকশন বাইপাস করবে
        run: pip install cloudscraper

      - name: Run python main.py
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          USER_COOKIE: ${{ secrets.USER_COOKIE }}
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tamashaweb.m3u || echo "No m3u file"
          git commit -m "Automated Playlist Refresh" || echo "No changes to commit"
          git push
